# Generated by Django 5.2 on 2025-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
